WebApplication/Controllers/LogController.cs
using ImageServer.WebApplication.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ImageServer.WebApplication.Controllers
{
    public class LogController : Controller
    {
        private static LogModel logModel = new LogModel();

        public LogController()
        {

            logModel.Notify -= Notify;
            logModel.Notify += Notify;
        }
        public void Notify()
        {
            Logs();
        }
        // GET: Log
        public ActionResult Logs()
        {
            return View(logModel);
        }
        [HttpPost]
        public ActionResult LogChangeFilter(FormCollection form)
        {
            string type = form["typeFilter"].ToString();
            logModel.FilterType = type;
            SelectedLogUpdate(type);
            return RedirectToAction("Logs");
        }
        public void SelectedLogUpdate(string type)
        {
            if (type != "")
            {
                logModel.SelectedLogMessages.Clear();
                foreach (Log item in logModel.Logs)
                {
                    if (item.Type == type)
                    {
                        logModel.AddToSelected(item);
                    }
                }
            }
            else
            {
                logModel.SelectedLogMessages.Clear();
            }
        }
    }
}

WebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - WebApplication</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("WebApplication", "Home", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Home", "Home")</li>
                    <li>@Html.ActionLink("Config", "Config", "Config")</li>
                    <li>@Html.ActionLink("Logs", "Logs", "Log")</li>
                    <li>@Html.ActionLink("Photos", "Photos", "Photos")</li>     
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - WebApplication</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>